name = "Menu Mate"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "zwxgkgwmt2g3jox6x71gtvs9"
  title = "Restaurant page banner upload"
  description = "the picture should be of aspect ratio 5:1 for best quality"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "sb4tgi5qzhswvbsdizzsqwcr"
  title = "Proposing changes on restaurant page"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "kzvbg1ks4xc7zi8q9q96w89m"
  title = "Delete title in hours open (unnecesarry)"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "yjteq0ft06fuabwtbz9ewr53"
  title = "Slight change on viewing restaurant page"
  description = """
Make the banner and font little smaller to make the restaurant items be the center of attention\r
"""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "eyyytp0voa8yf1w920dk4usz"
  title = "User page"
  description = "<p><strong>MY Description of the task</strong></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
